apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-img
  labels:
    app: eureka-img
spec:
  replicas: 3  # Number of pods to run
  selector:
    matchLabels:
      app: eureka-img
  template:
    metadata:
      labels:
        app: eureka-img
    spec:
      containers:
        - name: eureka-cntr
          image: sanjug16/eureka-img:latest  # Replace with your image name
          ports:
            - containerPort: 8761  # Port your Spring Boot app listens on
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-cntr
spec:
  selector:
    app: eureka-img
  ports:
    - protocol: TCP
      port: 8761  # Port exposed inside the Kubernetes cluster
      targetPort: 8761  # Port Spring Boot app listens on
  type: LoadBalancer  # Internal service (can change to LoadBalancer or NodePort)